// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk_android_jni.proto

package com.whensunset.wsvideoeditorsdk.model.jni;

public interface CreateProjectNativeReturnValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProject project = 1;</code>
   */
  boolean hasProject();
  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProject project = 1;</code>
   */
  com.whensunset.wsvideoeditorsdk.model.EditorProject getProject();

  /**
   * <code>optional int32 error_code = 2;</code>
   */
  int getErrorCode();
}
