// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk_android_jni.proto

package com.whensunset.wsvideoeditorsdk.model.jni;

/**
 * Protobuf type {@code whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue}
 */
public  final class CreateProjectNativeReturnValue extends
    com.google.protobuf.GeneratedMessageLite<
        CreateProjectNativeReturnValue, CreateProjectNativeReturnValue.Builder> implements
    // @@protoc_insertion_point(message_implements:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
    CreateProjectNativeReturnValueOrBuilder {
  private CreateProjectNativeReturnValue() {
  }
  public static final int PROJECT_FIELD_NUMBER = 1;
  private com.whensunset.wsvideoeditorsdk.model.EditorProject project_;
  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProject project = 1;</code>
   */
  public boolean hasProject() {
    return project_ != null;
  }
  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProject project = 1;</code>
   */
  public com.whensunset.wsvideoeditorsdk.model.EditorProject getProject() {
    return project_ == null ? com.whensunset.wsvideoeditorsdk.model.EditorProject.getDefaultInstance() : project_;
  }
  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProject project = 1;</code>
   */
  private void setProject(com.whensunset.wsvideoeditorsdk.model.EditorProject value) {
    if (value == null) {
      throw new NullPointerException();
    }
    project_ = value;
    
    }
  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProject project = 1;</code>
   */
  private void setProject(
      com.whensunset.wsvideoeditorsdk.model.EditorProject.Builder builderForValue) {
    project_ = builderForValue.build();
    
  }
  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProject project = 1;</code>
   */
  private void mergeProject(com.whensunset.wsvideoeditorsdk.model.EditorProject value) {
    if (project_ != null &&
        project_ != com.whensunset.wsvideoeditorsdk.model.EditorProject.getDefaultInstance()) {
      project_ =
        com.whensunset.wsvideoeditorsdk.model.EditorProject.newBuilder(project_).mergeFrom(value).buildPartial();
    } else {
      project_ = value;
    }
    
  }
  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProject project = 1;</code>
   */
  private void clearProject() {  project_ = null;
    
  }

  public static final int ERROR_CODE_FIELD_NUMBER = 2;
  private int errorCode_;
  /**
   * <code>optional int32 error_code = 2;</code>
   */
  public int getErrorCode() {
    return errorCode_;
  }
  /**
   * <code>optional int32 error_code = 2;</code>
   */
  private void setErrorCode(int value) {
    
    errorCode_ = value;
  }
  /**
   * <code>optional int32 error_code = 2;</code>
   */
  private void clearErrorCode() {
    
    errorCode_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (project_ != null) {
      output.writeMessage(1, getProject());
    }
    if (errorCode_ != 0) {
      output.writeInt32(2, errorCode_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (project_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getProject());
    }
    if (errorCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, errorCode_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue, Builder> implements
      // @@protoc_insertion_point(builder_implements:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
      com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValueOrBuilder {
    // Construct using com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .whensunset.wsvideoeditor.model.EditorProject project = 1;</code>
     */
    public boolean hasProject() {
      return instance.hasProject();
    }
    /**
     * <code>optional .whensunset.wsvideoeditor.model.EditorProject project = 1;</code>
     */
    public com.whensunset.wsvideoeditorsdk.model.EditorProject getProject() {
      return instance.getProject();
    }
    /**
     * <code>optional .whensunset.wsvideoeditor.model.EditorProject project = 1;</code>
     */
    public Builder setProject(com.whensunset.wsvideoeditorsdk.model.EditorProject value) {
      copyOnWrite();
      instance.setProject(value);
      return this;
      }
    /**
     * <code>optional .whensunset.wsvideoeditor.model.EditorProject project = 1;</code>
     */
    public Builder setProject(
        com.whensunset.wsvideoeditorsdk.model.EditorProject.Builder builderForValue) {
      copyOnWrite();
      instance.setProject(builderForValue);
      return this;
    }
    /**
     * <code>optional .whensunset.wsvideoeditor.model.EditorProject project = 1;</code>
     */
    public Builder mergeProject(com.whensunset.wsvideoeditorsdk.model.EditorProject value) {
      copyOnWrite();
      instance.mergeProject(value);
      return this;
    }
    /**
     * <code>optional .whensunset.wsvideoeditor.model.EditorProject project = 1;</code>
     */
    public Builder clearProject() {  copyOnWrite();
      instance.clearProject();
      return this;
    }

    /**
     * <code>optional int32 error_code = 2;</code>
     */
    public int getErrorCode() {
      return instance.getErrorCode();
    }
    /**
     * <code>optional int32 error_code = 2;</code>
     */
    public Builder setErrorCode(int value) {
      copyOnWrite();
      instance.setErrorCode(value);
      return this;
    }
    /**
     * <code>optional int32 error_code = 2;</code>
     */
    public Builder clearErrorCode() {
      copyOnWrite();
      instance.clearErrorCode();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue other = (com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue) arg1;
        project_ = visitor.visitMessage(project_, other.project_);
        errorCode_ = visitor.visitInt(errorCode_ != 0, errorCode_,
            other.errorCode_ != 0, other.errorCode_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.whensunset.wsvideoeditorsdk.model.EditorProject.Builder subBuilder = null;
                if (project_ != null) {
                  subBuilder = project_.toBuilder();
                }
                project_ = input.readMessage(com.whensunset.wsvideoeditorsdk.model.EditorProject.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(project_);
                  project_ = subBuilder.buildPartial();
                }

                break;
              }
              case 16: {

                errorCode_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
  private static final com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CreateProjectNativeReturnValue();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.whensunset.wsvideoeditorsdk.model.jni.CreateProjectNativeReturnValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CreateProjectNativeReturnValue> PARSER;

  public static com.google.protobuf.Parser<CreateProjectNativeReturnValue> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

