// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk_android_jni.proto

package com.whensunset.wsvideoeditorsdk.model.jni;

public final class WsVideoEditorSdkAndroidJni {
  private WsVideoEditorSdkAndroidJni() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
