/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_whensunset_wsvideoeditorsdk_WsVideoEditorUtils */

#ifndef _Included_com_whensunset_wsvideoeditorsdk_WsVideoEditorUtils
#define _Included_com_whensunset_wsvideoeditorsdk_WsVideoEditorUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_whensunset_wsvideoeditorsdk_WsVideoEditorUtils
 * Method:    initJniNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_whensunset_wsvideoeditorsdk_WsVideoEditorUtils_initJniNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
