/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_whensunset_wsvideoeditorsdk_WsMediaPlayer */

#ifndef _Included_com_whensunset_wsvideoeditorsdk_WsMediaPlayer
#define _Included_com_whensunset_wsvideoeditorsdk_WsMediaPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_whensunset_wsvideoeditorsdk_WsMediaPlayer
 * Method:    newNativePlayer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_whensunset_wsvideoeditorsdk_WsMediaPlayer_newNativePlayer
  (JNIEnv *, jobject);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_WsMediaPlayer
 * Method:    deleteNativePlayer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_whensunset_wsvideoeditorsdk_WsMediaPlayer_deleteNativePlayer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_WsMediaPlayer
 * Method:    setProjectNative
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_whensunset_wsvideoeditorsdk_WsMediaPlayer_setProjectNative
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_WsMediaPlayer
 * Method:    loadProjectNative
 * Signature: (J[BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_whensunset_wsvideoeditorsdk_WsMediaPlayer_loadProjectNative
  (JNIEnv *, jobject, jlong, jbyteArray, jboolean);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_WsMediaPlayer
 * Method:    drawFrameNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_whensunset_wsvideoeditorsdk_WsMediaPlayer_drawFrameNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_WsMediaPlayer
 * Method:    onAttachedViewNative
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_whensunset_wsvideoeditorsdk_WsMediaPlayer_onAttachedViewNative
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_WsMediaPlayer
 * Method:    onDetachedViewNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_whensunset_wsvideoeditorsdk_WsMediaPlayer_onDetachedViewNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_WsMediaPlayer
 * Method:    seekNative
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_whensunset_wsvideoeditorsdk_WsMediaPlayer_seekNative
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_WsMediaPlayer
 * Method:    playNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_whensunset_wsvideoeditorsdk_WsMediaPlayer_playNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_WsMediaPlayer
 * Method:    pauseNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_whensunset_wsvideoeditorsdk_WsMediaPlayer_pauseNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_WsMediaPlayer
 * Method:    isPlayingNative
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_whensunset_wsvideoeditorsdk_WsMediaPlayer_isPlayingNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_WsMediaPlayer
 * Method:    getCurrentTimeNative
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_whensunset_wsvideoeditorsdk_WsMediaPlayer_getCurrentTimeNative
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
