// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk.proto

package com.whensunset.wsvideoeditorsdk.model;

/**
 * <pre>
 * 表示一个多媒体编辑项目
 * </pre>
 *
 * Protobuf type {@code whensunset.wsvideoeditor.model.EditorProject}
 */
public  final class EditorProject extends
    com.google.protobuf.GeneratedMessageLite<
        EditorProject, EditorProject.Builder> implements
    // @@protoc_insertion_point(message_implements:whensunset.wsvideoeditor.model.EditorProject)
    EditorProjectOrBuilder {
  private EditorProject() {
    mediaAsset_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int PROJECT_ID_FIELD_NUMBER = 1;
  private long projectId_;
  /**
   * <code>optional int64 project_id = 1;</code>
   */
  public long getProjectId() {
    return projectId_;
  }
  /**
   * <code>optional int64 project_id = 1;</code>
   */
  private void setProjectId(long value) {
    
    projectId_ = value;
  }
  /**
   * <code>optional int64 project_id = 1;</code>
   */
  private void clearProjectId() {
    
    projectId_ = 0L;
  }

  public static final int MEDIA_ASSET_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<com.whensunset.wsvideoeditorsdk.model.MediaAsset> mediaAsset_;
  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  public java.util.List<com.whensunset.wsvideoeditorsdk.model.MediaAsset> getMediaAssetList() {
    return mediaAsset_;
  }
  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  public java.util.List<? extends com.whensunset.wsvideoeditorsdk.model.MediaAssetOrBuilder> 
      getMediaAssetOrBuilderList() {
    return mediaAsset_;
  }
  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  public int getMediaAssetCount() {
    return mediaAsset_.size();
  }
  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  public com.whensunset.wsvideoeditorsdk.model.MediaAsset getMediaAsset(int index) {
    return mediaAsset_.get(index);
  }
  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  public com.whensunset.wsvideoeditorsdk.model.MediaAssetOrBuilder getMediaAssetOrBuilder(
      int index) {
    return mediaAsset_.get(index);
  }
  private void ensureMediaAssetIsMutable() {
    if (!mediaAsset_.isModifiable()) {
      mediaAsset_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(mediaAsset_);
     }
  }

  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  private void setMediaAsset(
      int index, com.whensunset.wsvideoeditorsdk.model.MediaAsset value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureMediaAssetIsMutable();
    mediaAsset_.set(index, value);
  }
  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  private void setMediaAsset(
      int index, com.whensunset.wsvideoeditorsdk.model.MediaAsset.Builder builderForValue) {
    ensureMediaAssetIsMutable();
    mediaAsset_.set(index, builderForValue.build());
  }
  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  private void addMediaAsset(com.whensunset.wsvideoeditorsdk.model.MediaAsset value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureMediaAssetIsMutable();
    mediaAsset_.add(value);
  }
  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  private void addMediaAsset(
      int index, com.whensunset.wsvideoeditorsdk.model.MediaAsset value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureMediaAssetIsMutable();
    mediaAsset_.add(index, value);
  }
  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  private void addMediaAsset(
      com.whensunset.wsvideoeditorsdk.model.MediaAsset.Builder builderForValue) {
    ensureMediaAssetIsMutable();
    mediaAsset_.add(builderForValue.build());
  }
  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  private void addMediaAsset(
      int index, com.whensunset.wsvideoeditorsdk.model.MediaAsset.Builder builderForValue) {
    ensureMediaAssetIsMutable();
    mediaAsset_.add(index, builderForValue.build());
  }
  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  private void addAllMediaAsset(
      java.lang.Iterable<? extends com.whensunset.wsvideoeditorsdk.model.MediaAsset> values) {
    ensureMediaAssetIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, mediaAsset_);
  }
  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  private void clearMediaAsset() {
    mediaAsset_ = emptyProtobufList();
  }
  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  private void removeMediaAsset(int index) {
    ensureMediaAssetIsMutable();
    mediaAsset_.remove(index);
  }

  public static final int PRIVATE_DATA_FIELD_NUMBER = 3;
  private com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData privateData_;
  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProjectPrivateData private_data = 3;</code>
   */
  public boolean hasPrivateData() {
    return privateData_ != null;
  }
  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProjectPrivateData private_data = 3;</code>
   */
  public com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData getPrivateData() {
    return privateData_ == null ? com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData.getDefaultInstance() : privateData_;
  }
  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProjectPrivateData private_data = 3;</code>
   */
  private void setPrivateData(com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData value) {
    if (value == null) {
      throw new NullPointerException();
    }
    privateData_ = value;
    
    }
  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProjectPrivateData private_data = 3;</code>
   */
  private void setPrivateData(
      com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData.Builder builderForValue) {
    privateData_ = builderForValue.build();
    
  }
  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProjectPrivateData private_data = 3;</code>
   */
  private void mergePrivateData(com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData value) {
    if (privateData_ != null &&
        privateData_ != com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData.getDefaultInstance()) {
      privateData_ =
        com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData.newBuilder(privateData_).mergeFrom(value).buildPartial();
    } else {
      privateData_ = value;
    }
    
  }
  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProjectPrivateData private_data = 3;</code>
   */
  private void clearPrivateData() {  privateData_ = null;
    
  }

  public static final int BLUR_PADDING_AREA_FIELD_NUMBER = 4;
  private boolean blurPaddingArea_;
  /**
   * <pre>
   * 是否填充高斯模糊
   * </pre>
   *
   * <code>optional bool blur_padding_area = 4;</code>
   */
  public boolean getBlurPaddingArea() {
    return blurPaddingArea_;
  }
  /**
   * <pre>
   * 是否填充高斯模糊
   * </pre>
   *
   * <code>optional bool blur_padding_area = 4;</code>
   */
  private void setBlurPaddingArea(boolean value) {
    
    blurPaddingArea_ = value;
  }
  /**
   * <pre>
   * 是否填充高斯模糊
   * </pre>
   *
   * <code>optional bool blur_padding_area = 4;</code>
   */
  private void clearBlurPaddingArea() {
    
    blurPaddingArea_ = false;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (projectId_ != 0L) {
      output.writeInt64(1, projectId_);
    }
    for (int i = 0; i < mediaAsset_.size(); i++) {
      output.writeMessage(2, mediaAsset_.get(i));
    }
    if (privateData_ != null) {
      output.writeMessage(3, getPrivateData());
    }
    if (blurPaddingArea_ != false) {
      output.writeBool(4, blurPaddingArea_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (projectId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, projectId_);
    }
    for (int i = 0; i < mediaAsset_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, mediaAsset_.get(i));
    }
    if (privateData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPrivateData());
    }
    if (blurPaddingArea_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, blurPaddingArea_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.whensunset.wsvideoeditorsdk.model.EditorProject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.whensunset.wsvideoeditorsdk.model.EditorProject prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * 表示一个多媒体编辑项目
   * </pre>
   *
   * Protobuf type {@code whensunset.wsvideoeditor.model.EditorProject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.whensunset.wsvideoeditorsdk.model.EditorProject, Builder> implements
      // @@protoc_insertion_point(builder_implements:whensunset.wsvideoeditor.model.EditorProject)
      com.whensunset.wsvideoeditorsdk.model.EditorProjectOrBuilder {
    // Construct using com.whensunset.wsvideoeditorsdk.model.EditorProject.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int64 project_id = 1;</code>
     */
    public long getProjectId() {
      return instance.getProjectId();
    }
    /**
     * <code>optional int64 project_id = 1;</code>
     */
    public Builder setProjectId(long value) {
      copyOnWrite();
      instance.setProjectId(value);
      return this;
    }
    /**
     * <code>optional int64 project_id = 1;</code>
     */
    public Builder clearProjectId() {
      copyOnWrite();
      instance.clearProjectId();
      return this;
    }

    /**
     * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
     */
    public java.util.List<com.whensunset.wsvideoeditorsdk.model.MediaAsset> getMediaAssetList() {
      return java.util.Collections.unmodifiableList(
          instance.getMediaAssetList());
    }
    /**
     * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
     */
    public int getMediaAssetCount() {
      return instance.getMediaAssetCount();
    }/**
     * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
     */
    public com.whensunset.wsvideoeditorsdk.model.MediaAsset getMediaAsset(int index) {
      return instance.getMediaAsset(index);
    }
    /**
     * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
     */
    public Builder setMediaAsset(
        int index, com.whensunset.wsvideoeditorsdk.model.MediaAsset value) {
      copyOnWrite();
      instance.setMediaAsset(index, value);
      return this;
    }
    /**
     * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
     */
    public Builder setMediaAsset(
        int index, com.whensunset.wsvideoeditorsdk.model.MediaAsset.Builder builderForValue) {
      copyOnWrite();
      instance.setMediaAsset(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
     */
    public Builder addMediaAsset(com.whensunset.wsvideoeditorsdk.model.MediaAsset value) {
      copyOnWrite();
      instance.addMediaAsset(value);
      return this;
    }
    /**
     * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
     */
    public Builder addMediaAsset(
        int index, com.whensunset.wsvideoeditorsdk.model.MediaAsset value) {
      copyOnWrite();
      instance.addMediaAsset(index, value);
      return this;
    }
    /**
     * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
     */
    public Builder addMediaAsset(
        com.whensunset.wsvideoeditorsdk.model.MediaAsset.Builder builderForValue) {
      copyOnWrite();
      instance.addMediaAsset(builderForValue);
      return this;
    }
    /**
     * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
     */
    public Builder addMediaAsset(
        int index, com.whensunset.wsvideoeditorsdk.model.MediaAsset.Builder builderForValue) {
      copyOnWrite();
      instance.addMediaAsset(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
     */
    public Builder addAllMediaAsset(
        java.lang.Iterable<? extends com.whensunset.wsvideoeditorsdk.model.MediaAsset> values) {
      copyOnWrite();
      instance.addAllMediaAsset(values);
      return this;
    }
    /**
     * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
     */
    public Builder clearMediaAsset() {
      copyOnWrite();
      instance.clearMediaAsset();
      return this;
    }
    /**
     * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
     */
    public Builder removeMediaAsset(int index) {
      copyOnWrite();
      instance.removeMediaAsset(index);
      return this;
    }

    /**
     * <code>optional .whensunset.wsvideoeditor.model.EditorProjectPrivateData private_data = 3;</code>
     */
    public boolean hasPrivateData() {
      return instance.hasPrivateData();
    }
    /**
     * <code>optional .whensunset.wsvideoeditor.model.EditorProjectPrivateData private_data = 3;</code>
     */
    public com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData getPrivateData() {
      return instance.getPrivateData();
    }
    /**
     * <code>optional .whensunset.wsvideoeditor.model.EditorProjectPrivateData private_data = 3;</code>
     */
    public Builder setPrivateData(com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData value) {
      copyOnWrite();
      instance.setPrivateData(value);
      return this;
      }
    /**
     * <code>optional .whensunset.wsvideoeditor.model.EditorProjectPrivateData private_data = 3;</code>
     */
    public Builder setPrivateData(
        com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData.Builder builderForValue) {
      copyOnWrite();
      instance.setPrivateData(builderForValue);
      return this;
    }
    /**
     * <code>optional .whensunset.wsvideoeditor.model.EditorProjectPrivateData private_data = 3;</code>
     */
    public Builder mergePrivateData(com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData value) {
      copyOnWrite();
      instance.mergePrivateData(value);
      return this;
    }
    /**
     * <code>optional .whensunset.wsvideoeditor.model.EditorProjectPrivateData private_data = 3;</code>
     */
    public Builder clearPrivateData() {  copyOnWrite();
      instance.clearPrivateData();
      return this;
    }

    /**
     * <pre>
     * 是否填充高斯模糊
     * </pre>
     *
     * <code>optional bool blur_padding_area = 4;</code>
     */
    public boolean getBlurPaddingArea() {
      return instance.getBlurPaddingArea();
    }
    /**
     * <pre>
     * 是否填充高斯模糊
     * </pre>
     *
     * <code>optional bool blur_padding_area = 4;</code>
     */
    public Builder setBlurPaddingArea(boolean value) {
      copyOnWrite();
      instance.setBlurPaddingArea(value);
      return this;
    }
    /**
     * <pre>
     * 是否填充高斯模糊
     * </pre>
     *
     * <code>optional bool blur_padding_area = 4;</code>
     */
    public Builder clearBlurPaddingArea() {
      copyOnWrite();
      instance.clearBlurPaddingArea();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:whensunset.wsvideoeditor.model.EditorProject)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.whensunset.wsvideoeditorsdk.model.EditorProject();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        mediaAsset_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.whensunset.wsvideoeditorsdk.model.EditorProject other = (com.whensunset.wsvideoeditorsdk.model.EditorProject) arg1;
        projectId_ = visitor.visitLong(projectId_ != 0L, projectId_,
            other.projectId_ != 0L, other.projectId_);
        mediaAsset_= visitor.visitList(mediaAsset_, other.mediaAsset_);
        privateData_ = visitor.visitMessage(privateData_, other.privateData_);
        blurPaddingArea_ = visitor.visitBoolean(blurPaddingArea_ != false, blurPaddingArea_,
            other.blurPaddingArea_ != false, other.blurPaddingArea_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                projectId_ = input.readInt64();
                break;
              }
              case 18: {
                if (!mediaAsset_.isModifiable()) {
                  mediaAsset_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(mediaAsset_);
                }
                mediaAsset_.add(
                    input.readMessage(com.whensunset.wsvideoeditorsdk.model.MediaAsset.parser(), extensionRegistry));
                break;
              }
              case 26: {
                com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData.Builder subBuilder = null;
                if (privateData_ != null) {
                  subBuilder = privateData_.toBuilder();
                }
                privateData_ = input.readMessage(com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(privateData_);
                  privateData_ = subBuilder.buildPartial();
                }

                break;
              }
              case 32: {

                blurPaddingArea_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.whensunset.wsvideoeditorsdk.model.EditorProject.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:whensunset.wsvideoeditor.model.EditorProject)
  private static final com.whensunset.wsvideoeditorsdk.model.EditorProject DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new EditorProject();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.whensunset.wsvideoeditorsdk.model.EditorProject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<EditorProject> PARSER;

  public static com.google.protobuf.Parser<EditorProject> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

