// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk.proto

package com.whensunset.wsvideoeditorsdk.model;

public interface EditorProjectPrivateDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:whensunset.wsvideoeditor.model.EditorProjectPrivateData)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 project_width = 1;</code>
   */
  int getProjectWidth();

  /**
   * <code>optional int32 project_height = 2;</code>
   */
  int getProjectHeight();

  /**
   * <code>optional double project_fps = 3;</code>
   */
  double getProjectFps();

  /**
   * <code>optional double project_duration = 4;</code>
   */
  double getProjectDuration();

  /**
   * <code>optional int32 input_media_assets_number = 5;</code>
   */
  int getInputMediaAssetsNumber();
}
