// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk.proto

package com.whensunset.wsvideoeditorsdk.model;

public interface EditorProjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:whensunset.wsvideoeditor.model.EditorProject)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int64 project_id = 1;</code>
   */
  long getProjectId();

  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  java.util.List<com.whensunset.wsvideoeditorsdk.model.MediaAsset> 
      getMediaAssetList();
  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  com.whensunset.wsvideoeditorsdk.model.MediaAsset getMediaAsset(int index);
  /**
   * <code>repeated .whensunset.wsvideoeditor.model.MediaAsset media_asset = 2;</code>
   */
  int getMediaAssetCount();

  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProjectPrivateData private_data = 3;</code>
   */
  boolean hasPrivateData();
  /**
   * <code>optional .whensunset.wsvideoeditor.model.EditorProjectPrivateData private_data = 3;</code>
   */
  com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData getPrivateData();

  /**
   * <pre>
   * 是否填充高斯模糊
   * </pre>
   *
   * <code>optional bool blur_padding_area = 4;</code>
   */
  boolean getBlurPaddingArea();
}
