// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk.proto

package com.whensunset.wsvideoeditorsdk.model;

/**
 * <pre>
 * EditorProject 被解析之后获取到的数据
 * </pre>
 *
 * Protobuf type {@code whensunset.wsvideoeditor.model.EditorProjectPrivateData}
 */
public  final class EditorProjectPrivateData extends
    com.google.protobuf.GeneratedMessageLite<
        EditorProjectPrivateData, EditorProjectPrivateData.Builder> implements
    // @@protoc_insertion_point(message_implements:whensunset.wsvideoeditor.model.EditorProjectPrivateData)
    EditorProjectPrivateDataOrBuilder {
  private EditorProjectPrivateData() {
  }
  public static final int PROJECT_WIDTH_FIELD_NUMBER = 1;
  private int projectWidth_;
  /**
   * <code>optional int32 project_width = 1;</code>
   */
  public int getProjectWidth() {
    return projectWidth_;
  }
  /**
   * <code>optional int32 project_width = 1;</code>
   */
  private void setProjectWidth(int value) {
    
    projectWidth_ = value;
  }
  /**
   * <code>optional int32 project_width = 1;</code>
   */
  private void clearProjectWidth() {
    
    projectWidth_ = 0;
  }

  public static final int PROJECT_HEIGHT_FIELD_NUMBER = 2;
  private int projectHeight_;
  /**
   * <code>optional int32 project_height = 2;</code>
   */
  public int getProjectHeight() {
    return projectHeight_;
  }
  /**
   * <code>optional int32 project_height = 2;</code>
   */
  private void setProjectHeight(int value) {
    
    projectHeight_ = value;
  }
  /**
   * <code>optional int32 project_height = 2;</code>
   */
  private void clearProjectHeight() {
    
    projectHeight_ = 0;
  }

  public static final int PROJECT_FPS_FIELD_NUMBER = 3;
  private double projectFps_;
  /**
   * <code>optional double project_fps = 3;</code>
   */
  public double getProjectFps() {
    return projectFps_;
  }
  /**
   * <code>optional double project_fps = 3;</code>
   */
  private void setProjectFps(double value) {
    
    projectFps_ = value;
  }
  /**
   * <code>optional double project_fps = 3;</code>
   */
  private void clearProjectFps() {
    
    projectFps_ = 0D;
  }

  public static final int PROJECT_DURATION_FIELD_NUMBER = 4;
  private double projectDuration_;
  /**
   * <code>optional double project_duration = 4;</code>
   */
  public double getProjectDuration() {
    return projectDuration_;
  }
  /**
   * <code>optional double project_duration = 4;</code>
   */
  private void setProjectDuration(double value) {
    
    projectDuration_ = value;
  }
  /**
   * <code>optional double project_duration = 4;</code>
   */
  private void clearProjectDuration() {
    
    projectDuration_ = 0D;
  }

  public static final int INPUT_MEDIA_ASSETS_NUMBER_FIELD_NUMBER = 5;
  private int inputMediaAssetsNumber_;
  /**
   * <code>optional int32 input_media_assets_number = 5;</code>
   */
  public int getInputMediaAssetsNumber() {
    return inputMediaAssetsNumber_;
  }
  /**
   * <code>optional int32 input_media_assets_number = 5;</code>
   */
  private void setInputMediaAssetsNumber(int value) {
    
    inputMediaAssetsNumber_ = value;
  }
  /**
   * <code>optional int32 input_media_assets_number = 5;</code>
   */
  private void clearInputMediaAssetsNumber() {
    
    inputMediaAssetsNumber_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (projectWidth_ != 0) {
      output.writeInt32(1, projectWidth_);
    }
    if (projectHeight_ != 0) {
      output.writeInt32(2, projectHeight_);
    }
    if (projectFps_ != 0D) {
      output.writeDouble(3, projectFps_);
    }
    if (projectDuration_ != 0D) {
      output.writeDouble(4, projectDuration_);
    }
    if (inputMediaAssetsNumber_ != 0) {
      output.writeInt32(5, inputMediaAssetsNumber_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (projectWidth_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, projectWidth_);
    }
    if (projectHeight_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, projectHeight_);
    }
    if (projectFps_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, projectFps_);
    }
    if (projectDuration_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, projectDuration_);
    }
    if (inputMediaAssetsNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, inputMediaAssetsNumber_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * EditorProject 被解析之后获取到的数据
   * </pre>
   *
   * Protobuf type {@code whensunset.wsvideoeditor.model.EditorProjectPrivateData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData, Builder> implements
      // @@protoc_insertion_point(builder_implements:whensunset.wsvideoeditor.model.EditorProjectPrivateData)
      com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateDataOrBuilder {
    // Construct using com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int32 project_width = 1;</code>
     */
    public int getProjectWidth() {
      return instance.getProjectWidth();
    }
    /**
     * <code>optional int32 project_width = 1;</code>
     */
    public Builder setProjectWidth(int value) {
      copyOnWrite();
      instance.setProjectWidth(value);
      return this;
    }
    /**
     * <code>optional int32 project_width = 1;</code>
     */
    public Builder clearProjectWidth() {
      copyOnWrite();
      instance.clearProjectWidth();
      return this;
    }

    /**
     * <code>optional int32 project_height = 2;</code>
     */
    public int getProjectHeight() {
      return instance.getProjectHeight();
    }
    /**
     * <code>optional int32 project_height = 2;</code>
     */
    public Builder setProjectHeight(int value) {
      copyOnWrite();
      instance.setProjectHeight(value);
      return this;
    }
    /**
     * <code>optional int32 project_height = 2;</code>
     */
    public Builder clearProjectHeight() {
      copyOnWrite();
      instance.clearProjectHeight();
      return this;
    }

    /**
     * <code>optional double project_fps = 3;</code>
     */
    public double getProjectFps() {
      return instance.getProjectFps();
    }
    /**
     * <code>optional double project_fps = 3;</code>
     */
    public Builder setProjectFps(double value) {
      copyOnWrite();
      instance.setProjectFps(value);
      return this;
    }
    /**
     * <code>optional double project_fps = 3;</code>
     */
    public Builder clearProjectFps() {
      copyOnWrite();
      instance.clearProjectFps();
      return this;
    }

    /**
     * <code>optional double project_duration = 4;</code>
     */
    public double getProjectDuration() {
      return instance.getProjectDuration();
    }
    /**
     * <code>optional double project_duration = 4;</code>
     */
    public Builder setProjectDuration(double value) {
      copyOnWrite();
      instance.setProjectDuration(value);
      return this;
    }
    /**
     * <code>optional double project_duration = 4;</code>
     */
    public Builder clearProjectDuration() {
      copyOnWrite();
      instance.clearProjectDuration();
      return this;
    }

    /**
     * <code>optional int32 input_media_assets_number = 5;</code>
     */
    public int getInputMediaAssetsNumber() {
      return instance.getInputMediaAssetsNumber();
    }
    /**
     * <code>optional int32 input_media_assets_number = 5;</code>
     */
    public Builder setInputMediaAssetsNumber(int value) {
      copyOnWrite();
      instance.setInputMediaAssetsNumber(value);
      return this;
    }
    /**
     * <code>optional int32 input_media_assets_number = 5;</code>
     */
    public Builder clearInputMediaAssetsNumber() {
      copyOnWrite();
      instance.clearInputMediaAssetsNumber();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:whensunset.wsvideoeditor.model.EditorProjectPrivateData)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData other = (com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData) arg1;
        projectWidth_ = visitor.visitInt(projectWidth_ != 0, projectWidth_,
            other.projectWidth_ != 0, other.projectWidth_);
        projectHeight_ = visitor.visitInt(projectHeight_ != 0, projectHeight_,
            other.projectHeight_ != 0, other.projectHeight_);
        projectFps_ = visitor.visitDouble(projectFps_ != 0D, projectFps_,
            other.projectFps_ != 0D, other.projectFps_);
        projectDuration_ = visitor.visitDouble(projectDuration_ != 0D, projectDuration_,
            other.projectDuration_ != 0D, other.projectDuration_);
        inputMediaAssetsNumber_ = visitor.visitInt(inputMediaAssetsNumber_ != 0, inputMediaAssetsNumber_,
            other.inputMediaAssetsNumber_ != 0, other.inputMediaAssetsNumber_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                projectWidth_ = input.readInt32();
                break;
              }
              case 16: {

                projectHeight_ = input.readInt32();
                break;
              }
              case 25: {

                projectFps_ = input.readDouble();
                break;
              }
              case 33: {

                projectDuration_ = input.readDouble();
                break;
              }
              case 40: {

                inputMediaAssetsNumber_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:whensunset.wsvideoeditor.model.EditorProjectPrivateData)
  private static final com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new EditorProjectPrivateData();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.whensunset.wsvideoeditorsdk.model.EditorProjectPrivateData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<EditorProjectPrivateData> PARSER;

  public static com.google.protobuf.Parser<EditorProjectPrivateData> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

