// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk.proto

package com.whensunset.wsvideoeditorsdk.model;

public interface MediaStreamHolderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:whensunset.wsvideoeditor.model.MediaStreamHolder)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * 视频的长和宽
   * </pre>
   *
   * <code>optional int32 width = 1;</code>
   */
  int getWidth();

  /**
   * <code>optional int32 height = 2;</code>
   */
  int getHeight();

  /**
   * <pre>
   * 编解码器的名称
   * </pre>
   *
   * <code>optional string codec_type = 3;</code>
   */
  java.lang.String getCodecType();
  /**
   * <pre>
   * 编解码器的名称
   * </pre>
   *
   * <code>optional string codec_type = 3;</code>
   */
  com.google.protobuf.ByteString
      getCodecTypeBytes();

  /**
   * <pre>
   * 视频的旋转角度
   * </pre>
   *
   * <code>optional int32 rotation = 4;</code>
   */
  int getRotation();
}
