// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk.proto

package com.whensunset.wsvideoeditorsdk.model;

public interface MediaFileHolderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:whensunset.wsvideoeditor.model.MediaFileHolder)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string path = 1;</code>
   */
  java.lang.String getPath();
  /**
   * <code>optional string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <pre>
   * 文件的后缀名
   * </pre>
   *
   * <code>optional string format_name = 2;</code>
   */
  java.lang.String getFormatName();
  /**
   * <pre>
   * 文件的后缀名
   * </pre>
   *
   * <code>optional string format_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getFormatNameBytes();

  /**
   * <code>optional int32 probe_score = 3;</code>
   */
  int getProbeScore();

  /**
   * <pre>
   * 文件中的多媒体数据流的数量
   * </pre>
   *
   * <code>optional int32 num_streams = 4;</code>
   */
  int getNumStreams();

  /**
   * <pre>
   * 文件中的多媒体数据流的信息列表
   * </pre>
   *
   * <code>repeated .whensunset.wsvideoeditor.model.MediaStreamHolder streams = 5;</code>
   */
  java.util.List<com.whensunset.wsvideoeditorsdk.model.MediaStreamHolder> 
      getStreamsList();
  /**
   * <pre>
   * 文件中的多媒体数据流的信息列表
   * </pre>
   *
   * <code>repeated .whensunset.wsvideoeditor.model.MediaStreamHolder streams = 5;</code>
   */
  com.whensunset.wsvideoeditorsdk.model.MediaStreamHolder getStreams(int index);
  /**
   * <pre>
   * 文件中的多媒体数据流的信息列表
   * </pre>
   *
   * <code>repeated .whensunset.wsvideoeditor.model.MediaStreamHolder streams = 5;</code>
   */
  int getStreamsCount();

  /**
   * <pre>
   * 文件中多媒体信息流中最优的视频流
   * </pre>
   *
   * <code>optional int32 media_strema_index = 6;</code>
   */
  int getMediaStremaIndex();

  /**
   * <pre>
   * 文件中多媒体信息流中最优的音频流
   * </pre>
   *
   * <code>optional int32 audio_strema_index = 7;</code>
   */
  int getAudioStremaIndex();

  /**
   * <pre>
   * 时长
   * </pre>
   *
   * <code>optional double duration = 8;</code>
   */
  double getDuration();
}
