// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk.proto

package com.whensunset.wsvideoeditorsdk.model;

public interface MediaAssetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:whensunset.wsvideoeditor.model.MediaAsset)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * 相同表示当前素材是同样的
   * </pre>
   *
   * <code>optional uint64 asset_id = 1;</code>
   */
  long getAssetId();

  /**
   * <code>optional string asset_path = 2;</code>
   */
  java.lang.String getAssetPath();
  /**
   * <code>optional string asset_path = 2;</code>
   */
  com.google.protobuf.ByteString
      getAssetPathBytes();

  /**
   * <code>optional .whensunset.wsvideoeditor.model.MediaFileHolder media_asset_file_holder = 3;</code>
   */
  boolean hasMediaAssetFileHolder();
  /**
   * <code>optional .whensunset.wsvideoeditor.model.MediaFileHolder media_asset_file_holder = 3;</code>
   */
  com.whensunset.wsvideoeditorsdk.model.MediaFileHolder getMediaAssetFileHolder();

  /**
   * <pre>
   * 当前素材被剪裁的时间区域
   * </pre>
   *
   * <code>repeated .whensunset.wsvideoeditor.model.TimeRange clipped_time_range = 4;</code>
   */
  java.util.List<com.whensunset.wsvideoeditorsdk.model.TimeRange> 
      getClippedTimeRangeList();
  /**
   * <pre>
   * 当前素材被剪裁的时间区域
   * </pre>
   *
   * <code>repeated .whensunset.wsvideoeditor.model.TimeRange clipped_time_range = 4;</code>
   */
  com.whensunset.wsvideoeditorsdk.model.TimeRange getClippedTimeRange(int index);
  /**
   * <pre>
   * 当前素材被剪裁的时间区域
   * </pre>
   *
   * <code>repeated .whensunset.wsvideoeditor.model.TimeRange clipped_time_range = 4;</code>
   */
  int getClippedTimeRangeCount();

  /**
   * <pre>
   * 声音大小
   * </pre>
   *
   * <code>optional double volume = 5;</code>
   */
  double getVolume();

  /**
   * <code>optional .whensunset.wsvideoeditor.model.MediaAssetScaleType media_asset_scale_type = 6;</code>
   */
  int getMediaAssetScaleTypeValue();
  /**
   * <code>optional .whensunset.wsvideoeditor.model.MediaAssetScaleType media_asset_scale_type = 6;</code>
   */
  com.whensunset.wsvideoeditorsdk.model.MediaAssetScaleType getMediaAssetScaleType();

  /**
   * <code>optional .whensunset.wsvideoeditor.model.YuvAlphaType alpha_info = 7;</code>
   */
  int getAlphaInfoValue();
  /**
   * <code>optional .whensunset.wsvideoeditor.model.YuvAlphaType alpha_info = 7;</code>
   */
  com.whensunset.wsvideoeditorsdk.model.YuvAlphaType getAlphaInfo();
}
