// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk.proto

package com.whensunset.wsvideoeditorsdk.model;

public interface RationalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:whensunset.wsvideoeditor.model.Rational)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int64 num = 1;</code>
   */
  long getNum();

  /**
   * <code>optional int64 den = 2;</code>
   */
  long getDen();
}
