// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk.proto

package com.whensunset.wsvideoeditorsdk.model;

/**
 * <pre>
 * 用于保存一段时间，单位是秒
 * </pre>
 *
 * Protobuf type {@code whensunset.wsvideoeditor.model.TimeRange}
 */
public  final class TimeRange extends
    com.google.protobuf.GeneratedMessageLite<
        TimeRange, TimeRange.Builder> implements
    // @@protoc_insertion_point(message_implements:whensunset.wsvideoeditor.model.TimeRange)
    TimeRangeOrBuilder {
  private TimeRange() {
  }
  public static final int START_FIELD_NUMBER = 1;
  private double start_;
  /**
   * <code>optional double start = 1;</code>
   */
  public double getStart() {
    return start_;
  }
  /**
   * <code>optional double start = 1;</code>
   */
  private void setStart(double value) {
    
    start_ = value;
  }
  /**
   * <code>optional double start = 1;</code>
   */
  private void clearStart() {
    
    start_ = 0D;
  }

  public static final int DURATION_FIELD_NUMBER = 2;
  private double duration_;
  /**
   * <code>optional double duration = 2;</code>
   */
  public double getDuration() {
    return duration_;
  }
  /**
   * <code>optional double duration = 2;</code>
   */
  private void setDuration(double value) {
    
    duration_ = value;
  }
  /**
   * <code>optional double duration = 2;</code>
   */
  private void clearDuration() {
    
    duration_ = 0D;
  }

  public static final int ID_FIELD_NUMBER = 3;
  private long id_;
  /**
   * <code>optional uint64 id = 3;</code>
   */
  public long getId() {
    return id_;
  }
  /**
   * <code>optional uint64 id = 3;</code>
   */
  private void setId(long value) {
    
    id_ = value;
  }
  /**
   * <code>optional uint64 id = 3;</code>
   */
  private void clearId() {
    
    id_ = 0L;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (start_ != 0D) {
      output.writeDouble(1, start_);
    }
    if (duration_ != 0D) {
      output.writeDouble(2, duration_);
    }
    if (id_ != 0L) {
      output.writeUInt64(3, id_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (start_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, start_);
    }
    if (duration_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, duration_);
    }
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, id_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.whensunset.wsvideoeditorsdk.model.TimeRange parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.whensunset.wsvideoeditorsdk.model.TimeRange parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.TimeRange parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.whensunset.wsvideoeditorsdk.model.TimeRange parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.TimeRange parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.whensunset.wsvideoeditorsdk.model.TimeRange parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.TimeRange parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.whensunset.wsvideoeditorsdk.model.TimeRange parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.whensunset.wsvideoeditorsdk.model.TimeRange parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.whensunset.wsvideoeditorsdk.model.TimeRange parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.whensunset.wsvideoeditorsdk.model.TimeRange prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * 用于保存一段时间，单位是秒
   * </pre>
   *
   * Protobuf type {@code whensunset.wsvideoeditor.model.TimeRange}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.whensunset.wsvideoeditorsdk.model.TimeRange, Builder> implements
      // @@protoc_insertion_point(builder_implements:whensunset.wsvideoeditor.model.TimeRange)
      com.whensunset.wsvideoeditorsdk.model.TimeRangeOrBuilder {
    // Construct using com.whensunset.wsvideoeditorsdk.model.TimeRange.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional double start = 1;</code>
     */
    public double getStart() {
      return instance.getStart();
    }
    /**
     * <code>optional double start = 1;</code>
     */
    public Builder setStart(double value) {
      copyOnWrite();
      instance.setStart(value);
      return this;
    }
    /**
     * <code>optional double start = 1;</code>
     */
    public Builder clearStart() {
      copyOnWrite();
      instance.clearStart();
      return this;
    }

    /**
     * <code>optional double duration = 2;</code>
     */
    public double getDuration() {
      return instance.getDuration();
    }
    /**
     * <code>optional double duration = 2;</code>
     */
    public Builder setDuration(double value) {
      copyOnWrite();
      instance.setDuration(value);
      return this;
    }
    /**
     * <code>optional double duration = 2;</code>
     */
    public Builder clearDuration() {
      copyOnWrite();
      instance.clearDuration();
      return this;
    }

    /**
     * <code>optional uint64 id = 3;</code>
     */
    public long getId() {
      return instance.getId();
    }
    /**
     * <code>optional uint64 id = 3;</code>
     */
    public Builder setId(long value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>optional uint64 id = 3;</code>
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:whensunset.wsvideoeditor.model.TimeRange)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.whensunset.wsvideoeditorsdk.model.TimeRange();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.whensunset.wsvideoeditorsdk.model.TimeRange other = (com.whensunset.wsvideoeditorsdk.model.TimeRange) arg1;
        start_ = visitor.visitDouble(start_ != 0D, start_,
            other.start_ != 0D, other.start_);
        duration_ = visitor.visitDouble(duration_ != 0D, duration_,
            other.duration_ != 0D, other.duration_);
        id_ = visitor.visitLong(id_ != 0L, id_,
            other.id_ != 0L, other.id_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 9: {

                start_ = input.readDouble();
                break;
              }
              case 17: {

                duration_ = input.readDouble();
                break;
              }
              case 24: {

                id_ = input.readUInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.whensunset.wsvideoeditorsdk.model.TimeRange.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:whensunset.wsvideoeditor.model.TimeRange)
  private static final com.whensunset.wsvideoeditorsdk.model.TimeRange DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TimeRange();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.whensunset.wsvideoeditorsdk.model.TimeRange getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TimeRange> PARSER;

  public static com.google.protobuf.Parser<TimeRange> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

