// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk.proto

package com.whensunset.wsvideoeditorsdk.model;

public interface TimeRangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:whensunset.wsvideoeditor.model.TimeRange)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional double start = 1;</code>
   */
  double getStart();

  /**
   * <code>optional double duration = 2;</code>
   */
  double getDuration();

  /**
   * <code>optional uint64 id = 3;</code>
   */
  long getId();
}
