// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk.proto

package com.whensunset.wsvideoeditorsdk.model;

/**
 * Protobuf enum {@code whensunset.wsvideoeditor.model.YuvAlphaType}
 */
public enum YuvAlphaType
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>YUV_ALPHA_TYPE_NONE = 0;</code>
   */
  YUV_ALPHA_TYPE_NONE(0),
  /**
   * <code>YUV_ALPHA_TYPE_LEFT_RIGHT = 1;</code>
   */
  YUV_ALPHA_TYPE_LEFT_RIGHT(1),
  /**
   * <code>YUV_ALPHA_TYPE_TOP_BOTTOM = 2;</code>
   */
  YUV_ALPHA_TYPE_TOP_BOTTOM(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>YUV_ALPHA_TYPE_NONE = 0;</code>
   */
  public static final int YUV_ALPHA_TYPE_NONE_VALUE = 0;
  /**
   * <code>YUV_ALPHA_TYPE_LEFT_RIGHT = 1;</code>
   */
  public static final int YUV_ALPHA_TYPE_LEFT_RIGHT_VALUE = 1;
  /**
   * <code>YUV_ALPHA_TYPE_TOP_BOTTOM = 2;</code>
   */
  public static final int YUV_ALPHA_TYPE_TOP_BOTTOM_VALUE = 2;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static YuvAlphaType valueOf(int value) {
    return forNumber(value);
  }

  public static YuvAlphaType forNumber(int value) {
    switch (value) {
      case 0: return YUV_ALPHA_TYPE_NONE;
      case 1: return YUV_ALPHA_TYPE_LEFT_RIGHT;
      case 2: return YUV_ALPHA_TYPE_TOP_BOTTOM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<YuvAlphaType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      YuvAlphaType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<YuvAlphaType>() {
          public YuvAlphaType findValueByNumber(int number) {
            return YuvAlphaType.forNumber(number);
          }
        };

  private final int value;

  private YuvAlphaType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:whensunset.wsvideoeditor.model.YuvAlphaType)
}

