// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk_android_jni.proto

#ifndef PROTOBUF_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto__INCLUDED
#define PROTOBUF_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "ws_video_editor_sdk.pb.h"
// @@protoc_insertion_point(includes)

namespace whensunset {
namespace wsvideoeditor {
namespace model {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto();
void protobuf_AssignDesc_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto();
void protobuf_ShutdownFile_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto();

class CreateProjectNativeReturnValue;

// ===================================================================

class CreateProjectNativeReturnValue : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue) */ {
 public:
  CreateProjectNativeReturnValue();
  virtual ~CreateProjectNativeReturnValue();

  CreateProjectNativeReturnValue(const CreateProjectNativeReturnValue& from);

  inline CreateProjectNativeReturnValue& operator=(const CreateProjectNativeReturnValue& from) {
    CopyFrom(from);
    return *this;
  }

  static const CreateProjectNativeReturnValue& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CreateProjectNativeReturnValue* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CreateProjectNativeReturnValue* other);

  // implements Message ----------------------------------------------

  inline CreateProjectNativeReturnValue* New() const { return New(NULL); }

  CreateProjectNativeReturnValue* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CreateProjectNativeReturnValue& from);
  void MergeFrom(const CreateProjectNativeReturnValue& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CreateProjectNativeReturnValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .whensunset.wsvideoeditor.model.EditorProject project = 1;
  bool has_project() const;
  void clear_project();
  static const int kProjectFieldNumber = 1;
  const ::whensunset::wsvideoeditor::model::EditorProject& project() const;
  ::whensunset::wsvideoeditor::model::EditorProject* mutable_project();
  ::whensunset::wsvideoeditor::model::EditorProject* release_project();
  void set_allocated_project(::whensunset::wsvideoeditor::model::EditorProject* project);

  // optional int32 error_code = 2;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 2;
  ::google::protobuf::int32 error_code() const;
  void set_error_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::whensunset::wsvideoeditor::model::EditorProject* project_;
  ::google::protobuf::int32 error_code_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto();
  #endif
  friend void protobuf_AssignDesc_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto();
  friend void protobuf_ShutdownFile_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto();

  void InitAsDefaultInstance();
  static CreateProjectNativeReturnValue* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CreateProjectNativeReturnValue

// optional .whensunset.wsvideoeditor.model.EditorProject project = 1;
inline bool CreateProjectNativeReturnValue::has_project() const {
  return !_is_default_instance_ && project_ != NULL;
}
inline void CreateProjectNativeReturnValue::clear_project() {
  if (GetArenaNoVirtual() == NULL && project_ != NULL) delete project_;
  project_ = NULL;
}
inline const ::whensunset::wsvideoeditor::model::EditorProject& CreateProjectNativeReturnValue::project() const {
  // @@protoc_insertion_point(field_get:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue.project)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return project_ != NULL ? *project_ : *default_instance().project_;
#else
  return project_ != NULL ? *project_ : *default_instance_->project_;
#endif
}
inline ::whensunset::wsvideoeditor::model::EditorProject* CreateProjectNativeReturnValue::mutable_project() {
  
  if (project_ == NULL) {
    project_ = new ::whensunset::wsvideoeditor::model::EditorProject;
  }
  // @@protoc_insertion_point(field_mutable:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue.project)
  return project_;
}
inline ::whensunset::wsvideoeditor::model::EditorProject* CreateProjectNativeReturnValue::release_project() {
  // @@protoc_insertion_point(field_release:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue.project)
  
  ::whensunset::wsvideoeditor::model::EditorProject* temp = project_;
  project_ = NULL;
  return temp;
}
inline void CreateProjectNativeReturnValue::set_allocated_project(::whensunset::wsvideoeditor::model::EditorProject* project) {
  delete project_;
  project_ = project;
  if (project) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue.project)
}

// optional int32 error_code = 2;
inline void CreateProjectNativeReturnValue::clear_error_code() {
  error_code_ = 0;
}
inline ::google::protobuf::int32 CreateProjectNativeReturnValue::error_code() const {
  // @@protoc_insertion_point(field_get:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue.error_code)
  return error_code_;
}
inline void CreateProjectNativeReturnValue::set_error_code(::google::protobuf::int32 value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue.error_code)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace model
}  // namespace wsvideoeditor
}  // namespace whensunset

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto__INCLUDED
