// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws_video_editor_sdk_android_jni.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ws_video_editor_sdk_android_jni.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace whensunset {
namespace wsvideoeditor {
namespace model {

void protobuf_ShutdownFile_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto() {
  delete CreateProjectNativeReturnValue::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ::whensunset::wsvideoeditor::model::protobuf_AddDesc_ws_5fvideo_5feditor_5fsdk_2eproto();
  CreateProjectNativeReturnValue::default_instance_ = new CreateProjectNativeReturnValue();
  CreateProjectNativeReturnValue::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto_once_);
void protobuf_AddDesc_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto_once_,
                 &protobuf_AddDesc_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto {
  StaticDescriptorInitializer_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto() {
    protobuf_AddDesc_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto();
  }
} static_descriptor_initializer_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto_;
#endif

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CreateProjectNativeReturnValue::kProjectFieldNumber;
const int CreateProjectNativeReturnValue::kErrorCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CreateProjectNativeReturnValue::CreateProjectNativeReturnValue()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
}

void CreateProjectNativeReturnValue::InitAsDefaultInstance() {
  _is_default_instance_ = true;
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  project_ = const_cast< ::whensunset::wsvideoeditor::model::EditorProject*>(
      ::whensunset::wsvideoeditor::model::EditorProject::internal_default_instance());
#else
  project_ = const_cast< ::whensunset::wsvideoeditor::model::EditorProject*>(&::whensunset::wsvideoeditor::model::EditorProject::default_instance());
#endif
}

CreateProjectNativeReturnValue::CreateProjectNativeReturnValue(const CreateProjectNativeReturnValue& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
}

void CreateProjectNativeReturnValue::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  project_ = NULL;
  error_code_ = 0;
}

CreateProjectNativeReturnValue::~CreateProjectNativeReturnValue() {
  // @@protoc_insertion_point(destructor:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
  SharedDtor();
}

void CreateProjectNativeReturnValue::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete project_;
  }
}

void CreateProjectNativeReturnValue::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const CreateProjectNativeReturnValue& CreateProjectNativeReturnValue::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_ws_5fvideo_5feditor_5fsdk_5fandroid_5fjni_2eproto();
#endif
  return *default_instance_;
}

CreateProjectNativeReturnValue* CreateProjectNativeReturnValue::default_instance_ = NULL;

CreateProjectNativeReturnValue* CreateProjectNativeReturnValue::New(::google::protobuf::Arena* arena) const {
  CreateProjectNativeReturnValue* n = new CreateProjectNativeReturnValue;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CreateProjectNativeReturnValue::Clear() {
// @@protoc_insertion_point(message_clear_start:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
  if (GetArenaNoVirtual() == NULL && project_ != NULL) delete project_;
  project_ = NULL;
  error_code_ = 0;
}

bool CreateProjectNativeReturnValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .whensunset.wsvideoeditor.model.EditorProject project = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_project()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_error_code;
        break;
      }

      // optional int32 error_code = 2;
      case 2: {
        if (tag == 16) {
         parse_error_code:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
  return false;
#undef DO_
}

void CreateProjectNativeReturnValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
  // optional .whensunset.wsvideoeditor.model.EditorProject project = 1;
  if (this->has_project()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, *this->project_, output);
  }

  // optional int32 error_code = 2;
  if (this->error_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->error_code(), output);
  }

  // @@protoc_insertion_point(serialize_end:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
}

int CreateProjectNativeReturnValue::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
  int total_size = 0;

  // optional .whensunset.wsvideoeditor.model.EditorProject project = 1;
  if (this->has_project()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->project_);
  }

  // optional int32 error_code = 2;
  if (this->error_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error_code());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CreateProjectNativeReturnValue::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const CreateProjectNativeReturnValue*>(&from));
}

void CreateProjectNativeReturnValue::MergeFrom(const CreateProjectNativeReturnValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.has_project()) {
    mutable_project()->::whensunset::wsvideoeditor::model::EditorProject::MergeFrom(from.project());
  }
  if (from.error_code() != 0) {
    set_error_code(from.error_code());
  }
}

void CreateProjectNativeReturnValue::CopyFrom(const CreateProjectNativeReturnValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateProjectNativeReturnValue::IsInitialized() const {

  return true;
}

void CreateProjectNativeReturnValue::Swap(CreateProjectNativeReturnValue* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CreateProjectNativeReturnValue::InternalSwap(CreateProjectNativeReturnValue* other) {
  std::swap(project_, other->project_);
  std::swap(error_code_, other->error_code_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string CreateProjectNativeReturnValue::GetTypeName() const {
  return "whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CreateProjectNativeReturnValue

// optional .whensunset.wsvideoeditor.model.EditorProject project = 1;
bool CreateProjectNativeReturnValue::has_project() const {
  return !_is_default_instance_ && project_ != NULL;
}
void CreateProjectNativeReturnValue::clear_project() {
  if (GetArenaNoVirtual() == NULL && project_ != NULL) delete project_;
  project_ = NULL;
}
const ::whensunset::wsvideoeditor::model::EditorProject& CreateProjectNativeReturnValue::project() const {
  // @@protoc_insertion_point(field_get:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue.project)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return project_ != NULL ? *project_ : *default_instance().project_;
#else
  return project_ != NULL ? *project_ : *default_instance_->project_;
#endif
}
::whensunset::wsvideoeditor::model::EditorProject* CreateProjectNativeReturnValue::mutable_project() {
  
  if (project_ == NULL) {
    project_ = new ::whensunset::wsvideoeditor::model::EditorProject;
  }
  // @@protoc_insertion_point(field_mutable:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue.project)
  return project_;
}
::whensunset::wsvideoeditor::model::EditorProject* CreateProjectNativeReturnValue::release_project() {
  // @@protoc_insertion_point(field_release:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue.project)
  
  ::whensunset::wsvideoeditor::model::EditorProject* temp = project_;
  project_ = NULL;
  return temp;
}
void CreateProjectNativeReturnValue::set_allocated_project(::whensunset::wsvideoeditor::model::EditorProject* project) {
  delete project_;
  project_ = project;
  if (project) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue.project)
}

// optional int32 error_code = 2;
void CreateProjectNativeReturnValue::clear_error_code() {
  error_code_ = 0;
}
 ::google::protobuf::int32 CreateProjectNativeReturnValue::error_code() const {
  // @@protoc_insertion_point(field_get:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue.error_code)
  return error_code_;
}
 void CreateProjectNativeReturnValue::set_error_code(::google::protobuf::int32 value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:whensunset.wsvideoeditor.model.CreateProjectNativeReturnValue.error_code)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace model
}  // namespace wsvideoeditor
}  // namespace whensunset

// @@protoc_insertion_point(global_scope)
