/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService */

#ifndef _Included_com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService
#define _Included_com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService_newNative
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService
 * Method:    releaseNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService_releaseNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService
 * Method:    setProjectNative
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL
Java_com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService_setProjectNative
        (JNIEnv *, jobject, jlong, jdouble, jbyteArray);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService
 * Method:    startNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService_startNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService
 * Method:    getRenderFrameNative
 * Signature: (JD)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService_getRenderFrameNative
        (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService
 * Method:    updateProjectNative
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL
Java_com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService_updateProjectNative
        (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService
 * Method:    seekNative
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService_seekNative
        (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService
 * Method:    stopNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService_stopNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService
 * Method:    endedNative
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService_endedNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService
 * Method:    stoppedNative
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService_stoppedNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService
 * Method:    getBufferedFrameCountNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_com_whensunset_wsvideoeditorsdk_inner_VideoDecoderService_getBufferedFrameCountNative
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
